# Generated by Django 5.0.7 on 2024-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refbook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
