# Generated by Django 5.0.7 on 2024-07-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refbooks', '0002_alter_refbook_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionrefbook',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия версии'),
        ),
    ]
